---
- name: Checkout the latest dotfiles repo
  git:
    repo: https://github.com/jeliser/dotfiles.git
    dest: ~/.devel_dotfiles

- name: Install the pip dotfiles package
  pip:
    name: dotfiles

- name: Load the dotfiles
  shell: ./load_dotfiles.sh
  args:
    chdir: ~/.devel_dotfiles

