name: Yocto CI

on:
  push:
    paths:
    - 'yocto/**'

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v2
    - name: Build the YOCTO image
      run: docker build -t yocto:latest -f .Dockerfile .
      working-directory: ./yocto

